### ISSUE TITLE
Start up que to preform the jobs (locally)

### ISSUE THREAD

**Issue by marksuurland** [chanks/que#210] opened 2018-03-16 14:28 UTC
Hi guys,

I just started with Que, and got everything set up locally, my first job is located in the que_jobs table. Now I want to process it, by running something like: que --worker-count 1, like being mentioned here:
[https://github.com/chanks/que/blob/master/docs/managing_workers.md](https://github.com/chanks/que/blob/master/docs/managing_workers.md)

However I get the follow warning / message: 
`Unsupported logging level: info (try debug, info, warn, error, or fatal)`

What am I doing wrong?

Thanks again!

**Comment by chanks** [comment] 2018-03-16 14:33
Hmm, weird! You're not passing a `--log-level` option?

What ruby version are you running? The executable tries to map the log level setting to a constant under `Logger`, so I could see getting that message if `Logger::INFO` isn't defined for some reason, but I believe that's part of the standard library.

**Comment by marksuurland** [comment] 2018-03-16 14:35
Hi Chanks!

Thanks for the quick answer :), when running:
`que --worker-count 1 --log-level debug`
I get the same warning.

My ruby version is: ruby 2.2.5p319 (2016-04-26 revision 54774) [x86_64-darwin15]

**Comment by chanks** [comment] 2018-03-16 15:03
Hmm... That's very weird, I can't seem to reproduce it locally:

```
chris@lovelace ~ $ ruby -v
ruby 2.2.5p319 (2016-04-26 revision 54774) [x86_64-linux]
chris@lovelace ~ $ irb
2.2.5 :001 > RUBY_VERSION
 => "2.2.5" 
2.2.5 :002 > require 'logger'
 => true 
2.2.5 :003 > log_level = "info"
 => "info" 
2.2.5 :004 > Logger.const_get(log_level.upcase)
 => 1 
2.2.5 :005 > Logger::INFO
 => 1 
```

I wonder if there's anything in your Gemfile that's monkeypatching Logger, or has the same name so the wrong `logger` is being required? Though if that's true I think you'd have bigger problems...

**Comment by marksuurland** [comment] 2018-03-16 15:07
When trying the same as you:

```
Marks-MacBook-Pro:yrd_api marksuurland$ IRB
2.2.5 :001 > RUBY_VERSION
 => "2.2.5" 
2.2.5 :002 > require 'logger'
 => true 
2.2.5 :003 > log_level = "info"
 => "info" 
2.2.5 :004 > Logger.const_get(log_level.upcase)
 => 1 
2.2.5 :005 > Logger::INFO
 => 1 
```

I will check your suggestion if some gem monkeypatching Logger.

**Comment by marksuurland** [comment] 2018-03-18 08:26
@chanks How can I check which logger is being required? (To be sure the normal ruby logger is being used)

**Comment by chanks** [comment] 2018-03-18 12:56
Start up a console and compare `Que.logger` (or `Que.get_logger`, but all that does is call `Que.logger` if it's a proc) to the logger instance you expect it to use?

If you're using Rails, the Railtie should make sure that you're using `Rails.logger`.

**Comment by marksuurland** [comment] 2018-03-19 14:43
I'm using rails:

```
Running via Spring preloader in process 54238
Loading development environment (Rails 5.0.5)
2.2.5 :001 > Que.logger
 => #<Proc:0x007ff11a974b78@/Users/marksuurland/.rvm/gems/ruby-2.2.5/bundler/gems/que-fb94321b40f7/lib/que/rails/railtie.rb:10>
 
2.2.5 :002 > Que.get_logger
 => #<RailsStdoutLogging::StdoutLogger:0x007ff11b767f28 @progname=nil, @level=0, @default_formatter=#<Logger::Formatter:0x007ff11b767e88 @datetime_format=nil>, @formatter=#<ActiveSupport::Logger::SimpleFormatter:0x007ff11b767d98 @datetime_format=nil>, @logdev=#<Logger::LogDevice:0x007ff11b767e38 @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<IO:/dev/ttys003>, @mutex=#<Logger::LogDevice::LogDeviceMutex:0x007ff11b767e10 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Mutex:0x007ff11b767dc0>>>, @local_levels=#<Concurrent::Map:0x007ff11b767d48 entries=0 default_proc=nil>> 
```
Seems correct to me, do you spot anything unusual?

**Comment by chanks** [comment] 2018-03-19 18:21
Certainly looks Rails-esque. Are you able to do a Que.get_logger.level =
Logger::INFO in your app’s console?

**Comment by jvdp** [comment] 2018-03-28 11:35
The railtie defines `Que.logger` as `Que.logger = proc { ::Rails.logger }` (on master.)

But in `command_line_interface.rb` it's used as follows: `Que.logger.level = Logger.const_get(log_level.upcase)`. So I guess that should be `get_logger`?

**Comment by chanks** [comment] 2018-03-28 14:04
Hmm, that's a good point, I need to add tests for the CLI when the logger is callable. But I don't think that would raise the error Mark was getting :thinking:

**Comment by jvdp** [comment] 2018-03-28 14:11
It does, because of the rescue: https://github.com/chanks/que/blob/master/bin/command_line_interface.rb#L176 (calling `.level` on a `Proc` is a kind of `NameError`, it seems.)

**Comment by chanks** [comment] 2018-03-28 14:16
```ruby
NoMethodError < NameError #=> true
```

Huh, you learn something new every day! Thanks @jvdp! I'm at work now, but I'll fix this and push a new beta tonight.

**Comment by marksuurland** [comment] 2018-03-28 15:25
@chanks seems Im a good tester haha :) Let me know if I still need to check something

**Comment by chanks** [comment] 2018-03-28 22:04
I just pushed a fix for this to master. I'm going to wait a bit to release a beta, though, since there are other outstanding issues.

Sorry for the delay, @marksuurland!

**Closed by chanks** 2018-03-28 22:04 UTC
